# Generated by Django 4.0.3 on 2022-04-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_balance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
