# Generated by Django 4.0.3 on 2022-04-07 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Mylibrary', '0002_customuser_user_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('num_stars', models.CharField(choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star')], max_length=50, null=True)),
                ('number_of_rates', models.IntegerField(default=0)),
                ('book', models.FileField(upload_to='')),
                ('authors', models.ManyToManyField(blank=True, to='Mylibrary.author')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Mylibrary.publisher')),
            ],
        ),
    ]
