# Generated by Django 4.0.3 on 2022-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylibrary', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='num_stars',
            field=models.CharField(blank=True, choices=[('1 star', '1 star'), ('2 star', '2 star'), ('3 star', '3 star'), ('4 star', '4 star')], max_length=50, null=True),
        ),
    ]
