# Generated by Django 4.0.3 on 2022-04-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mylibrary', '0005_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='publisher',
        ),
    ]
