# Generated by Django 4.0.3 on 2022-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mylibrary', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
